"""Mask R-CNN training and single-scale evaluation settings."""

from copy import deepcopy


_BASE = {'auto_scale_lr': {'base_batch_size': 64, 'enable': False},
 'default_hooks': {'checkpoint': {'_scope_': 'mmdet',
                                  'interval': 1,
                                  'max_keep_ckpts': 1,
                                  'rule': 'greater',
                                  'save_best': 'coco/bbox_mAP',
                                  'type': 'CheckpointHook'},
                   'logger': {'_scope_': 'mmdet', 'interval': 10, 'type': 'LoggerHook'},
                   'param_scheduler': {'_scope_': 'mmdet', 'type': 'ParamSchedulerHook'},
                   'sampler_seed': {'_scope_': 'mmdet', 'type': 'DistSamplerSeedHook'},
                   'timer': {'_scope_': 'mmdet', 'type': 'IterTimerHook'},
                   'visualization': {'_scope_': 'mmdet', 'type': 'DetVisualizationHook'}},
 'default_scope': 'mmdet',
 'env_cfg': {'cudnn_benchmark': False,
             'dist_cfg': {'backend': 'nccl'},
             'mp_cfg': {'mp_start_method': 'fork', 'opencv_num_threads': 0}},
 'log_level': 'INFO',
 'log_processor': {'_scope_': 'mmdet', 'by_epoch': True, 'type': 'LogProcessor', 'window_size': 50},
 'model': {'_scope_': 'mmdet',
           'backbone': {'arch': 'tiny',
                        'channels_last': False,
                        'drop_path_rate': 0.2,
                        'init_cfg': None,
                        'norm_eval': True,
                        'out_indices': (0, 1, 2, 3),
                        'type': 'VisionHOPEBackbone',
                        'use_checkpoint': False},
           'data_preprocessor': {'bgr_to_rgb': True,
                                 'mean': [123.675, 116.28, 103.53],
                                 'pad_mask': True,
                                 'pad_size_divisor': 32,
                                 'std': [58.395, 57.12, 57.375],
                                 'type': 'DetDataPreprocessor'},
           'neck': {'in_channels': [64, 128, 256, 512],
                    'num_outs': 5,
                    'out_channels': 256,
                    'type': 'FPN'},
           'roi_head': {'bbox_head': {'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                                                     'target_stds': [0.1, 0.1, 0.2, 0.2],
                                                     'type': 'DeltaXYWHBBoxCoder'},
                                      'fc_out_channels': 1024,
                                      'in_channels': 256,
                                      'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
                                      'loss_cls': {'loss_weight': 1.0,
                                                   'type': 'CrossEntropyLoss',
                                                   'use_sigmoid': False},
                                      'num_classes': 80,
                                      'reg_class_agnostic': False,
                                      'roi_feat_size': 7,
                                      'type': 'Shared2FCBBoxHead'},
                        'bbox_roi_extractor': {'featmap_strides': [4, 8, 16, 32],
                                               'out_channels': 256,
                                               'roi_layer': {'output_size': 7,
                                                             'sampling_ratio': 0,
                                                             'type': 'RoIAlign'},
                                               'type': 'ContiguousRoIExtractor'},
                        'mask_head': {'conv_out_channels': 256,
                                      'in_channels': 256,
                                      'loss_mask': {'loss_weight': 1.0,
                                                    'type': 'CrossEntropyLoss',
                                                    'use_mask': True},
                                      'num_classes': 80,
                                      'num_convs': 4,
                                      'type': 'FCNMaskHead'},
                        'mask_roi_extractor': {'featmap_strides': [4, 8, 16, 32],
                                               'out_channels': 256,
                                               'roi_layer': {'output_size': 14,
                                                             'sampling_ratio': 0,
                                                             'type': 'RoIAlign'},
                                               'type': 'ContiguousRoIExtractor'},
                        'type': 'StandardRoIHead'},
           'rpn_head': {'anchor_generator': {'ratios': [0.5, 1.0, 2.0],
                                             'scales': [8],
                                             'strides': [4, 8, 16, 32, 64],
                                             'type': 'AnchorGenerator'},
                        'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                                       'target_stds': [1.0, 1.0, 1.0, 1.0],
                                       'type': 'DeltaXYWHBBoxCoder'},
                        'feat_channels': 256,
                        'in_channels': 256,
                        'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
                        'loss_cls': {'loss_weight': 1.0,
                                     'type': 'CrossEntropyLoss',
                                     'use_sigmoid': True},
                        'type': 'RPNHead'},
           'test_cfg': {'rcnn': {'mask_thr_binary': 0.5,
                                 'max_per_img': 100,
                                 'nms': {'iou_threshold': 0.5, 'type': 'nms'},
                                 'score_thr': 0.05},
                        'rpn': {'max_per_img': 1000,
                                'min_bbox_size': 0,
                                'nms': {'iou_threshold': 0.7, 'type': 'nms'},
                                'nms_pre': 1000}},
           'train_cfg': {'rcnn': {'assigner': {'ignore_iof_thr': -1,
                                               'match_low_quality': True,
                                               'min_pos_iou': 0.5,
                                               'neg_iou_thr': 0.5,
                                               'pos_iou_thr': 0.5,
                                               'type': 'MaxIoUAssigner'},
                                  'debug': False,
                                  'mask_size': 28,
                                  'pos_weight': -1,
                                  'sampler': {'add_gt_as_proposals': True,
                                              'neg_pos_ub': -1,
                                              'num': 512,
                                              'pos_fraction': 0.25,
                                              'type': 'RandomSampler'}},
                         'rpn': {'allowed_border': -1,
                                 'assigner': {'ignore_iof_thr': -1,
                                              'match_low_quality': True,
                                              'min_pos_iou': 0.3,
                                              'neg_iou_thr': 0.3,
                                              'pos_iou_thr': 0.7,
                                              'type': 'MaxIoUAssigner'},
                                 'debug': False,
                                 'pos_weight': -1,
                                 'sampler': {'add_gt_as_proposals': False,
                                             'neg_pos_ub': -1,
                                             'num': 256,
                                             'pos_fraction': 0.5,
                                             'type': 'RandomSampler'}},
                         'rpn_proposal': {'max_per_img': 1000,
                                          'min_bbox_size': 0,
                                          'nms': {'iou_threshold': 0.7, 'type': 'nms'},
                                          'nms_pre': 2000}},
           'type': 'MaskRCNN'},
 'optim_wrapper': {'_scope_': 'mmdet',
                   'dtype': 'float16',
                   'optimizer': {'betas': (0.9, 0.999),
                                 'lr': 0.0004,
                                 'type': 'AdamW',
                                 'weight_decay': 0.05},
                   'paramwise_cfg': {'bias_decay_mult': 0.0,
                                     'bypass_duplicate': True,
                                     'custom_keys': {'absolute_pos_embed': {'decay_mult': 0.0},
                                                     'norm': {'decay_mult': 0.0},
                                                     'relative_position_bias_table': {'decay_mult': 0.0}},
                                     'norm_decay_mult': 0.0},
                   'type': 'AmpOptimWrapper'},
 'param_scheduler': [{'begin': 0,
                      'by_epoch': False,
                      'end': 1000,
                      'start_factor': 0.001,
                      'type': 'LinearLR'},
                     {'begin': 0,
                      'by_epoch': True,
                      'end': 12,
                      'gamma': 0.1,
                      'milestones': [8, 11],
                      'type': 'MultiStepLR'}],
 'test_cfg': {'_scope_': 'mmdet', 'type': 'TestLoop'},
 'test_dataloader': {'batch_size': 1,
                     'dataset': {'_scope_': 'mmdet',
                                 'ann_file': 'annotations/instances_val2017.json',
                                 'backend_args': None,
                                 'data_prefix': {'img': 'val2017/'},
                                 'data_root': 'data/coco/',
                                 'pipeline': [{'backend_args': None, 'type': 'LoadImageFromFile'},
                                              {'keep_ratio': True,
                                               'scale': (1333, 800),
                                               'type': 'Resize'},
                                              {'type': 'LoadAnnotations',
                                               'with_bbox': True,
                                               'with_mask': True},
                                              {'meta_keys': ('img_id',
                                                             'img_path',
                                                             'ori_shape',
                                                             'img_shape',
                                                             'scale_factor'),
                                               'type': 'PackDetInputs'}],
                                 'test_mode': True,
                                 'type': 'CocoDataset'},
                     'drop_last': False,
                     'num_workers': 2,
                     'persistent_workers': True,
                     'sampler': {'_scope_': 'mmdet', 'shuffle': False, 'type': 'DefaultSampler'}},
 'test_evaluator': {'_scope_': 'mmdet',
                    'ann_file': 'data/coco/annotations/instances_val2017.json',
                    'backend_args': None,
                    'format_only': False,
                    'metric': ['bbox', 'segm'],
                    'type': 'CocoMetric'},
 'train_cfg': {'_scope_': 'mmdet',
               'max_epochs': 12,
               'type': 'EpochBasedTrainLoop',
               'val_interval': 1},
 'train_dataloader': {'batch_sampler': {'_scope_': 'mmdet', 'type': 'AspectRatioBatchSampler'},
                      'batch_size': 8,
                      'dataset': {'_scope_': 'mmdet',
                                  'ann_file': 'annotations/instances_train2017.json',
                                  'backend_args': None,
                                  'data_prefix': {'img': 'train2017/'},
                                  'data_root': 'data/coco/',
                                  'filter_cfg': {'filter_empty_gt': True, 'min_size': 32},
                                  'pipeline': [{'backend_args': None, 'type': 'LoadImageFromFile'},
                                               {'type': 'LoadAnnotations',
                                                'with_bbox': True,
                                                'with_mask': True},
                                               {'prob': 0.5, 'type': 'RandomFlip'},
                                               {'transforms': [[{'keep_ratio': True,
                                                                 'scales': [(480, 1333),
                                                                            (512, 1333),
                                                                            (544, 1333),
                                                                            (576, 1333),
                                                                            (608, 1333),
                                                                            (640, 1333),
                                                                            (672, 1333),
                                                                            (704, 1333),
                                                                            (736, 1333),
                                                                            (768, 1333),
                                                                            (800, 1333)],
                                                                 'type': 'RandomChoiceResize'}],
                                                               [{'keep_ratio': True,
                                                                 'scales': [(400, 1333),
                                                                            (500, 1333),
                                                                            (600, 1333)],
                                                                 'type': 'RandomChoiceResize'},
                                                                {'allow_negative_crop': True,
                                                                 'crop_size': (384, 600),
                                                                 'crop_type': 'absolute_range',
                                                                 'type': 'RandomCrop'},
                                                                {'keep_ratio': True,
                                                                 'scales': [(480, 1333),
                                                                            (512, 1333),
                                                                            (544, 1333),
                                                                            (576, 1333),
                                                                            (608, 1333),
                                                                            (640, 1333),
                                                                            (672, 1333),
                                                                            (704, 1333),
                                                                            (736, 1333),
                                                                            (768, 1333),
                                                                            (800, 1333)],
                                                                 'type': 'RandomChoiceResize'}]],
                                                'type': 'RandomChoice'},
                                               {'type': 'PackDetInputs'}],
                                  'type': 'CocoDataset'},
                      'num_workers': 4,
                      'persistent_workers': True,
                      'pin_memory': True,
                      'prefetch_factor': 4,
                      'sampler': {'_scope_': 'mmdet', 'shuffle': True, 'type': 'DefaultSampler'}},
 'val_cfg': {'_scope_': 'mmdet', 'type': 'ValLoop'},
 'val_dataloader': {'batch_size': 1,
                    'dataset': {'_scope_': 'mmdet',
                                'ann_file': 'annotations/instances_val2017.json',
                                'backend_args': None,
                                'data_prefix': {'img': 'val2017/'},
                                'data_root': 'data/coco/',
                                'pipeline': [{'backend_args': None, 'type': 'LoadImageFromFile'},
                                             {'keep_ratio': True,
                                              'scale': (1333, 800),
                                              'type': 'Resize'},
                                             {'type': 'LoadAnnotations',
                                              'with_bbox': True,
                                              'with_mask': True},
                                             {'meta_keys': ('img_id',
                                                            'img_path',
                                                            'ori_shape',
                                                            'img_shape',
                                                            'scale_factor'),
                                              'type': 'PackDetInputs'}],
                                'test_mode': True,
                                'type': 'CocoDataset'},
                    'drop_last': False,
                    'num_workers': 2,
                    'persistent_workers': True,
                    'sampler': {'_scope_': 'mmdet', 'shuffle': False, 'type': 'DefaultSampler'}},
 'val_evaluator': {'_scope_': 'mmdet',
                   'ann_file': 'data/coco/annotations/instances_val2017.json',
                   'backend_args': None,
                   'format_only': False,
                   'metric': ['bbox', 'segm'],
                   'type': 'CocoMetric'},
 'visualizer': {'_scope_': 'mmdet',
                'name': 'visualizer',
                'type': 'DetLocalVisualizer',
                'vis_backends': [{'type': 'LocalVisBackend'}]},
 'custom_imports': {'imports': ['visionhope.tasks.detection.registry'],
                    'allow_failed_imports': False},
 'launcher': 'none',
 'load_from': None,
 'resume': False,
 'work_dir': 'outputs/detection'}
def build_config(arch="tiny", schedule="1x"):
    """Build the Mask R-CNN base with the selected backbone and schedule."""
    if arch not in {"tiny", "small", "base"} or schedule not in {"1x", "3x"}:
        raise ValueError("Expected arch tiny/small/base and schedule 1x/3x")
    cfg = deepcopy(_BASE)
    backbone = cfg["model"]["backbone"]
    backbone["arch"] = arch
    widths = {"tiny": [64, 128, 256, 512], "small": [64, 160, 320, 512],
              "base": [96, 192, 448, 640]}
    cfg["model"]["neck"]["in_channels"] = widths[arch]
    if schedule == "3x":
        cfg["train_cfg"]["max_epochs"] = 36
        cfg["param_scheduler"][1].update(end=36, milestones=[27, 33])
    return cfg
