"""UPerNet training and single-scale evaluation settings."""

from copy import deepcopy


_BASE = {'default_hooks': {'checkpoint': {'_scope_': 'mmseg',
                                  'by_epoch': False,
                                  'interval': 8000,
                                  'max_keep_ckpts': 2,
                                  'rule': 'greater',
                                  'save_best': 'mIoU',
                                  'type': 'CheckpointHook'},
                   'logger': {'_scope_': 'mmseg',
                              'interval': 50,
                              'log_metric_by_epoch': False,
                              'type': 'LoggerHook'},
                   'param_scheduler': {'_scope_': 'mmseg', 'type': 'ParamSchedulerHook'},
                   'sampler_seed': {'_scope_': 'mmseg', 'type': 'DistSamplerSeedHook'},
                   'timer': {'_scope_': 'mmseg', 'type': 'IterTimerHook'},
                   'visualization': {'_scope_': 'mmseg', 'type': 'SegVisualizationHook'}},
 'default_scope': 'mmseg',
 'env_cfg': {'cudnn_benchmark': False,
             'dist_cfg': {'backend': 'nccl'},
             'mp_cfg': {'mp_start_method': 'fork', 'opencv_num_threads': 0}},
 'log_level': 'INFO',
 'log_processor': {'by_epoch': False},
 'model': {'_scope_': 'mmseg',
           'auxiliary_head': {'align_corners': False,
                              'channels': 256,
                              'concat_input': False,
                              'dropout_ratio': 0.1,
                              'in_channels': 256,
                              'in_index': 2,
                              'loss_decode': {'loss_weight': 0.4,
                                              'type': 'CrossEntropyLoss',
                                              'use_sigmoid': False},
                              'norm_cfg': {'requires_grad': True, 'type': 'SyncBN'},
                              'num_classes': 150,
                              'num_convs': 1,
                              'type': 'FCNHead'},
           'backbone': {'channels_last': True,
                        'drop_path_rate': 0.2,
                        'init_cfg': None,
                        'norm_eval': True,
                        'out_indices': (0, 1, 2, 3),
                        'type': 'VisionHOPEBackbone',
                        'use_checkpoint': False,
                        'arch': 'tiny'},
           'data_preprocessor': {'bgr_to_rgb': True,
                                 'mean': [123.675, 116.28, 103.53],
                                 'pad_val': 0,
                                 'seg_pad_val': 255,
                                 'size': (512, 512),
                                 'std': [58.395, 57.12, 57.375],
                                 'type': 'SegDataPreProcessor'},
           'decode_head': {'align_corners': False,
                           'channels': 512,
                           'dropout_ratio': 0.1,
                           'in_channels': [64, 128, 256, 512],
                           'in_index': [0, 1, 2, 3],
                           'loss_decode': {'loss_weight': 1.0,
                                           'type': 'CrossEntropyLoss',
                                           'use_sigmoid': False},
                           'norm_cfg': {'requires_grad': True, 'type': 'SyncBN'},
                           'num_classes': 150,
                           'pool_scales': (1, 2, 3, 6),
                           'type': 'UPerHead'},
           'pretrained': None,
           'test_cfg': {'mode': 'whole'},
           'train_cfg': {},
           'type': 'EncoderDecoder'},
 'optim_wrapper': {'optimizer': {'betas': (0.9, 0.999),
                                 'lr': 6e-05,
                                 'type': 'AdamW',
                                 'weight_decay': 0.01},
                   'paramwise_cfg': {'custom_keys': {'absolute_pos_embed': {'decay_mult': 0.0},
                                                     'norm': {'decay_mult': 0.0},
                                                     'relative_position_bias_table': {'decay_mult': 0.0}},
                                     'norm_decay_mult': 0.0},
                   'type': 'OptimWrapper'},
 'param_scheduler': [{'begin': 0,
                      'by_epoch': False,
                      'end': 1500,
                      'start_factor': 1e-06,
                      'type': 'LinearLR'},
                     {'begin': 1500,
                      'by_epoch': False,
                      'end': 160000,
                      'eta_min': 0.0,
                      'power': 1.0,
                      'type': 'PolyLR'}],
 'test_cfg': {'_scope_': 'mmseg', 'type': 'TestLoop'},
 'test_dataloader': {'batch_size': 1,
                     'dataset': {'_scope_': 'mmseg',
                                 'data_prefix': {'img_path': 'images/validation',
                                                 'seg_map_path': 'annotations/validation'},
                                 'data_root': 'data/ade20k',
                                 'pipeline': [{'type': 'LoadImageFromFile'},
                                              {'keep_ratio': True,
                                               'scale': (2048, 512),
                                               'type': 'Resize'},
                                              {'reduce_zero_label': True,
                                               'type': 'LoadAnnotations'},
                                              {'type': 'PackSegInputs'}],
                                 'type': 'ADE20KDataset'},
                     'num_workers': 2,
                     'persistent_workers': True,
                     'sampler': {'_scope_': 'mmseg', 'shuffle': False, 'type': 'DefaultSampler'}},
 'test_evaluator': {'_scope_': 'mmseg', 'iou_metrics': ['mIoU'], 'type': 'IoUMetric'},
 'train_cfg': {'_scope_': 'mmseg',
               'max_iters': 160000,
               'type': 'IterBasedTrainLoop',
               'val_interval': 8000},
 'train_dataloader': {'batch_size': 2,
                      'dataset': {'_scope_': 'mmseg',
                                  'data_prefix': {'img_path': 'images/training',
                                                  'seg_map_path': 'annotations/training'},
                                  'data_root': 'data/ade20k',
                                  'pipeline': [{'type': 'LoadImageFromFile'},
                                               {'reduce_zero_label': True,
                                                'type': 'LoadAnnotations'},
                                               {'keep_ratio': True,
                                                'ratio_range': (0.5, 2.0),
                                                'scale': (2048, 512),
                                                'type': 'RandomResize'},
                                               {'cat_max_ratio': 0.75,
                                                'crop_size': (512, 512),
                                                'type': 'RandomCrop'},
                                               {'prob': 0.5, 'type': 'RandomFlip'},
                                               {'type': 'PhotoMetricDistortion'},
                                               {'type': 'PackSegInputs'}],
                                  'type': 'ADE20KDataset'},
                      'num_workers': 4,
                      'persistent_workers': True,
                      'sampler': {'_scope_': 'mmseg', 'shuffle': True, 'type': 'InfiniteSampler'}},
 'val_cfg': {'_scope_': 'mmseg', 'type': 'ValLoop'},
 'val_dataloader': {'batch_size': 1,
                    'dataset': {'_scope_': 'mmseg',
                                'data_prefix': {'img_path': 'images/validation',
                                                'seg_map_path': 'annotations/validation'},
                                'data_root': 'data/ade20k',
                                'pipeline': [{'type': 'LoadImageFromFile'},
                                             {'keep_ratio': True,
                                              'scale': (2048, 512),
                                              'type': 'Resize'},
                                             {'reduce_zero_label': True, 'type': 'LoadAnnotations'},
                                             {'type': 'PackSegInputs'}],
                                'type': 'ADE20KDataset'},
                    'num_workers': 2,
                    'persistent_workers': True,
                    'sampler': {'_scope_': 'mmseg', 'shuffle': False, 'type': 'DefaultSampler'}},
 'val_evaluator': {'_scope_': 'mmseg', 'iou_metrics': ['mIoU'], 'type': 'IoUMetric'},
 'visualizer': {'_scope_': 'mmseg',
                'name': 'visualizer',
                'type': 'SegLocalVisualizer',
                'vis_backends': [{'type': 'LocalVisBackend'}]},
 'custom_imports': {'imports': ['visionhope.tasks.segmentation.registry'],
                    'allow_failed_imports': False},
 'launcher': 'none',
 'load_from': None,
 'resume': False,
 'work_dir': 'outputs/segmentation'}


def build_config(arch="tiny"):
    """Build the 160k-iteration UPerNet base with the selected backbone."""
    if arch not in {"tiny", "small", "base"}:
        raise ValueError("Expected arch tiny, small, or base")
    cfg = deepcopy(_BASE)
    cfg["model"]["backbone"]["arch"] = arch
    widths = {"tiny": [64, 128, 256, 512], "small": [64, 160, 320, 512],
              "base": [96, 192, 448, 640]}
    cfg["model"]["decode_head"]["in_channels"] = widths[arch]
    cfg["model"]["auxiliary_head"]["in_channels"] = widths[arch][2]
    return cfg
